export const USER_INIT = 'USER_INIT';
export const LOGOUT = 'LOGOUT';

export const FETCHING_ALL_NEWS_REQUEST = 'FETCHING_ALL_NEWS_REQUEST';
export const FETCHING_ALL_NEWS_SUCCESS = 'FETCHING_ALL_NEWS_SUCCESS';
export const FETCHING_ALL_NEWS_FAILED = 'FETCHING_ALL_NEWS_FAILED';

export const CREATE_NEWS_REQUEST = 'CREATE_NEWS_REQUEST';
export const CREATE_NEWS_SUCCESS = 'CREATE_NEWS_SUCCESS';
export const CREATE_NEWS_FAILED = 'CREATE_NEWS_FAILED';

export const FETCH_NEWS_REQUEST = 'FETCH_NEWS_REQUEST';
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_FAILED = 'FETCH_NEWS_FAILED';

export const EDIT_NEWS = 'EDIT_NEWS';
export const EDIT_NEWS_REQUEST = 'EDIT_NEWS_REQUEST';
export const EDIT_NEWS_SUCCESS = 'EDIT_NEWS_SUCCESS';
export const EDIT_NEWS_FAILED = 'EDIT_NEWS_FAILED';

export const DELETE_NEWS_REQUEST = 'DELETE_NEWS_REQUEST';
export const DELETE_NEWS_SUCCESS = 'DELETE_NEWS_SUCCESS';
export const DELETE_NEWS_FAILED = 'DELETE_NEWS_FAILED';
